name: build and deploy

on:
  schedule:
  - cron: "20 */4 * * *"
  push:

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Check
      run: |
        mypy .

    - name: Generate calendar
      run: |
        python main.py fetch-data-sources

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./gen
        publish_branch: gh-pages
        allow_empty_commit: false
        user_name: 'hsheth2-bot'
        user_email: 'github-bot@harshal.sheth.io'
        cname: yale-calendars.sheth.io
