name: test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install -r ./test_requirements.txt
    - name: Check
      run: |
        black --check .
        mypy .

    - name: Test calendar generation
      run: |
        python main.py generate
